# == This file defines the page_layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: standard
  elements: [company, contact, navbar]
  layoutpage: true

- name: team
  elements: [person, contact, navbar]

- name: intro
  unique: true
  elements: [slide_image, infographic, open_call, contact, location, navbar, partner, number, menu]
  layoutpage: true
  
- name: news
  unique: true
  elements: [notice]
  
- name: platforms
  unique: true
  elements: [platform]
