# == This file defines the page_layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: standard
  elements: [company, contact, navbar]
  layoutpage: true
  cache: false

- name: team
  elements: [person, contact, navbar]
  cache: false

- name: intro
  unique: true
  elements: [slide_image, infographic, open_call, contact, location, navbar, partner, number, menu, quotation, video, plain_image, shadowbox, quote_title]
  layoutpage: true
  cache: false
  
- name: news
  unique: true
  elements: [notice]
  cache: false
  
- name: platforms
  unique: true
  elements: [platform]
  cache: false
  
- name: accelerator
  unique: true
  elements: [accelerator]
  cache: false
  
- name: whitepage
  unique: true
  elements: [rich_text]
  cache: false